# -*- mode: ruby -*-
# vi: set ft=ruby :
# -*- coding: utf-8 -*-

Vagrant.configure("2") do |config|
  #Encoding.default_external = 'UTF-8'

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2222, auto_correct: "true"
  config.vm.network "private_network", ip: "192.168.33.91"

  config.vm.synced_folder "./", "/vagrant", type: "virtualbox", create:"true"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "practice_ruby"
    vb.gui = true
    vb.memory = "4096"
    vb.customize [
      "modifyvm", :id,
      "--vram", "256", 
      "--clipboard", "bidirectional",
      "--draganddrop", "bidirectional",
      "--cpus", "2",
      "--ioapic", "on"
    ]
  end
end
